### ISSUE TITLE
No Data on Panels with Oracle Enterprise Manager App Plugins 

### ISSUE THREAD

**Issue by TonyChan1113** [kartik468/grafana-generate-pdf-nodejs#6]
Hi, I'm using your code to export my dash board to PDF .It's run but the PDF file is like this.I searched everywhere but can't find the solution. 

[grafana_5.pdf](https://github.com/kartik468/grafana-generate-pdf-nodejs/files/11217606/grafana_5.pdf)

**Comment by kartik468** [comment]
@TonyChan1113  I have updated the script to support latest Grafana version 9.4.7. Can you check with this new script?

**Comment by TonyChan1113** [comment]
Thanks for your update, but it's still not working.  I used this command: `node grafana_pdf_newest.js "http://10.0.30.32:3000/d/YfYZfzE4k/sample-host-health-report?orgId=1&var-oem_gf_emsite=Oracle%20Enterprise%20Manager&var-oem_gf_target_type=host&var-oem_gf_target_name=oemcc" admin:admin output/grafana_host.pdf`. The dashboard has data but the pdf is not. Please help.
![host_health](https://user-images.githubusercontent.com/51502891/232370201-3dc19977-df2c-4028-aa2e-9795887f774e.PNG)
[grafana_host.pdf](https://github.com/kartik468/grafana-generate-pdf-nodejs/files/11245910/grafana_host.pdf)
 I use Grafana 8.2.7 and OEM 3.0.0. Thanks

**Comment by kartik468** [comment]
set headless to false in the script and check if you see the page correctly

**Comment by TonyChan1113** [comment]
`Error: Failed to launch the browser process!
[22800:22800:0417/103724.820687:ERROR:browser_main_loop.cc(1439)] Unable to open X display.
[0417/103724.827427:ERROR:nacl_helper_linux.cc(307)] NaCl helper process running without a sandbox!
Most likely you need to configure your SUID sandbox correctly


` 
It will cause an error like this. Thank you.

**Comment by kartik468** [comment]
to debug this it should open correctly with headless false.

**Comment by TonyChan1113** [comment]
Sorry I dont understand what you mean , I change the headless to false and it cause the error

**Comment by TonyChan1113** [comment]
I think the error is for No Data . PDF file is because the Code is for Grafana 9.4.7. Where could I find the code for Grafana 8.2.7? 
Thank you. 
It's because Oracle Plugin doesn't work on version 9.4.7

**Comment by emjhay2004** [comment]
> Thanks for your update, but it's still not working. I used this command: `node grafana_pdf_newest.js "http://10.0.30.32:3000/d/YfYZfzE4k/sample-host-health-report?orgId=1&var-oem_gf_emsite=Oracle%20Enterprise%20Manager&var-oem_gf_target_type=host&var-oem_gf_target_name=oemcc" admin:admin output/grafana_host.pdf`. The dashboard has data but the pdf is not. Please help. ![host_health](https://user-images.githubusercontent.com/51502891/232370201-3dc19977-df2c-4028-aa2e-9795887f774e.PNG) [grafana_host.pdf](https://github.com/kartik468/grafana-generate-pdf-nodejs/files/11245910/grafana_host.pdf) I use Grafana 8.2.7 and OEM 3.0.0. Thanks

Well it seems that using **admin:admin** for accessing of your hosted Grafana no longer works, you may try using API Key instead (refer to: https://gist.github.com/svet-b/1ad0656cd3ce0e1a633e16eb20f66425?permalink_comment_id=3867894#gistcomment-3867894).
